name = "bazelisk"
type = "cli"

[resolve]
git-url = "https://github.com/bazelbuild/bazelisk"

[platform.linux]
download-file = "bazelisk-linux-{arch}"

[platform.macos]
download-file = "bazelisk-darwin-{arch}"

[platform.windows]
download-file = "bazelisk-windows-{arch}"

[install]
download-url = "https://github.com/bazelbuild/bazelisk/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"
x86_64 = "amd64"
