name = "carapace"
type = "cli"

[resolve]
git-url = "https://github.com/carapace-sh/carapace-bin"

[platform.linux]
download-file = "carapace-bin_linux_{arch}.tar.gz"

[platform.macos]
download-file = "carapace-bin-_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "carapace-bin_windows_{arch}.zip"

[install]
download-url = "https://github.com/carapace-sh/carapace-bin/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "386"
x86_64 = "amd64"
aarch64 = "arm64"
