name = "cue"
type = "cli"

[resolve]
git-url = "https://github.com/cue-lang/cue"

[platform.linux]
archive_prefix = "cue_v{version}_linux_{arch}"
download-file = "cue_v{version}_linux_{arch}.tar.gz"

[platform.macos]
archive_prefix = "cue_v{version}_darwin_{arch}"
download-file = "cue_v{version}_darwin_{arch}.tar.gz"

[platform.windows]
archive_prefix = "cue_v{version}_windows_{arch}"
download-file = "cue_v{version}_windows_{arch}.tar.gz"

[install]
download-url = "https://github.com/cue-lang/cue/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/cue-lang/cue/releases/download/v{version}/checksums.txt"

[install.secondary.cuepls]
exe-path = "cuepls"

[install.arch]
x86 = "i686"
x86_64 = "amd64"
aarch64 = "arm64"
