name = "git-branchless"
type = "cli"

[resolve]
git-url = "https://github.com/arxanas/git-branchless/"

[platform.linux]
archive-prefix = "git-branchless-v{version}-{arch}-unknown-linux-{libc}"
download-file = "git-branchless-v{version}-{arch}-unknown-linux-{libc}.tar.gz"

[platform.macos]
archive-prefix = "git-branchless-v{version}-{arch}-apple-darwin"
download-file = "git-branchless-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
archive-prefix = "git-branchless-v{version}-{arch}-pc-windows-msvc"
download-file = "git-branchless-v{version}-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/arxanas/git-branchless/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"

[install.libc]
gnu = "musl"


