name = "git-cliff"
type = "cli"

[resolve]
git-url = "https://github.com/orhun/git-cliff/"

[platform.linux]
archive-prefix = "git-cliff-{version}"
download-file = "git-cliff-{version}-{arch}-unknown-linux-{libc}.tar.gz"
checksum-file = "git-cliff-{version}-{arch}-unknown-linux-{libc}.tar.gz.sha512"

[platform.macos]
archive-prefix = "git-cliff-{version}"
download-file = "git-cliff-{version}-{arch}-apple-darwin.tar.gz"
checksum-file = "git-cliff-{version}-{arch}-apple-darwin.tar.gz.sha512"

[platform.windows]
archive-prefix = "git-cliff-{version}"
download-file = "git-cliff-{version}-{arch}-pc-windows-msvc.zip"
checksum-file = "git-cliff-{version}-{arch}-pc-windows-msvc.zip.sha512"

[install]
download-url = "https://github.com/orhun/git-cliff/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"

[install.secondary.git-cliff-completions]
exe-path = "git-cliff-completions"
[install.secondary.git-cliff-mangen]
exe-path = "git-cliff-mangen"
