name = "github-release"
type = "cli"

[resolve]
git-url = "https://github.com/github-release/github-release"

[platform.linux]
archive-prefix = "bin/linux/{arch}"
download-file = "linux-{arch}-github-release.tar.bz2"

[platform.macos]
archive-prefix = "bin/darwin/{arch}"
download-file = "darwin-{arch}-github-release.tar.bz2"

[platform.windows]
archive-prefix = "bin/windows/{arch}"
download-file = "windows-{arch}-github-release.zip"

[install]
download-url = "https://github.com/github-release/github-release/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"
x86_64 = "amd64"
