name = "mdcat"
type = "cli"

[resolve]
git-url = "https://github.com/swsnr/mdcat"
version-pattern = "^mdcat-?((?<major>\\d+)\\.(?<minor>\\d+)(\\.(?<patch>\\d+))?)"

[platform.linux]
archive-prefix = "mdcat-{version}-{arch}-unknown-linux-{libc}"
download-file = "mdcat-{version}-{arch}-unknown-linux-{libc}.tar.gz"
checksum-file = "mdcat-{version}-{arch}-unknown-linux-{libc}.tar.gz.sha256"

[platform.macos]
archive-prefix = "mdcat-{version}-{arch}-apple-darwin"
download-file = "mdcat-{version}-{arch}-apple-darwin.tar.gz"
checksum-file = "mdcat-{version}-{arch}-apple-darwin.tar.gz.sha256"

[platform.windows]
archive-prefix = "mdcat-{version}-{arch}-pc-windows-msvc"
download-file = "mdcat-{version}-{arch}-pc-windows-msvc.zip"
checksum-file = "mdcat-{version}-{arch}-pc-windows-msvc.zip.sha256"

[install]
download-url = "https://github.com/swsnr/mdcat/releases/download/mdcat-{version}/{download_file}"

[install.arch]
x86 = "i686"

[install.libc]
gnu = "musl"
