name = "pre-commit"
type = "cli"

[resolve]
git-url = "https://github.com/pre-commit/pre-commit"

[platform.linux]
download-file = "pre-commit-{version}.pyz"

[platform.macos]
download-file = "pre-commit-{version}.pyz"

[platform.windows]
download-file = "pre-commit-{version}.pyz"

[install]
download-url = "https://github.com/pre-commit/pre-commit/releases/download/v{version}/{download_file}"

[install.primary]
parent-exe-name = "python3"
