name = "xh"
type = "cli"

[resolve]
git-url = "https://github.com/ducaale/xh"

[platform.linux]
archive-prefix = "xh-v{version}-{arch}-unknown-linux-{libc}"
download-file = "xh-v{version}-{arch}-unknown-linux-{libc}.tar.gz"

[platform.macos]
archive-prefix = "xh-v{version}-{arch}-apple-darwin"
download-file = "xh-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
archive-prefix = "xh-v{version}-{arch}-pc-windows-msvc"
download-file = "xh-v{version}-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/ducaale/xh/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"

[install.libc]
gnu = "musl"
