name = "diffedit3"
type = "cli"

[resolve]
git-url = "https://github.com/ilyagr/diffedit3"

[platform.linux]
archive-prefix = "diffedit3-v{version}-{arch}-unknown-linux-{libc}"
download-file = "diffedit3-v{version}-{arch}-unknown-linux-{libc}.tar.gz"

[platform.macos]
archive-prefix = "diffedit3-v{version}-{arch}-apple-darwin"
download-file = "diffedit3-v{version}-{arch}-apple-darwin.tar.gz"

[platform.windows]
archive-prefix = "diffedit3-v{version}-{arch}-pc-windows-msvc"
download-file = "diffedit3-v{version}-{arch}-pc-windows-msvc.zip"

[install]
download-url = "https://github.com/ilyagr/diffedit3/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "i686"

[install.libc]
gnu = "musl"

